export DBHOST="af-aho-mariadb-svr.mariadb.database.azure.com"
export DBUSER="afroahodbadmin@af-aho-mariadb-svr"
export DBNAME="aho_azure_database"
export DBPASS="AFr578!%$2020"
export SSL_CERT_FILE="/home/site/cert/BaltimoreCyberTrustRoot.crt.pem"
