# Generated by Django 2.1.2 on 2020-07-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthfacilitytranslation',
            name='shortname',
            field=models.CharField(default='NotAvailable', max_length=230, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownershiptranslation',
            name='email',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownershiptranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Facility Owner'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownershiptranslation',
            name='posta',
            field=models.CharField(blank=True, max_length=500, verbose_name='Postal Address'),
        ),
    ]
