# Generated by Django 2.2.12 on 2020-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='year_established',
        ),
        migrations.AddField(
            model_name='stghealthfacility',
            name='admin_location',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='Administrative Location'),
        ),
        migrations.AddField(
            model_name='stghealthfacility',
            name='geosource',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Geo-source (LL source)'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cloded', 'Closed')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
