# Generated by Django 2.2.12 on 2020-11-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20201114_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
