# Generated by Django 2.1.2 on 2020-07-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20200728_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthfacility',
            name='email',
            field=models.CharField(default='admin@mtccl.co.ke', max_length=250, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stghealthfacilitytranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
