# Generated by Django 2.1.2 on 2020-07-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20200728_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='email',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityOwnership', verbose_name='facility Ownership'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityType', verbose_name='Facility Type'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='url',
            field=models.CharField(blank=True, max_length=2083, null=True, verbose_name='Web Address'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Physical Address'),
        ),
    ]
