# Generated by Django 2.2.12 on 2020-11-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20201114_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgfacilityownership',
            name='location',
        ),
    ]
