# Generated by Django 2.1.2 on 2020-07-30 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20200728_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgfacilityownershiptranslation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='stgfacilityownershiptranslation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='stgfacilityownershiptranslation',
            name='posta',
        ),
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='email',
        ),
        migrations.AddField(
            model_name='stghealthfacilitytranslation',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='stghealthfacilitytranslation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone format: '+999999999' maximum 15.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='url',
            field=models.URLField(blank=True, max_length=2083, null=True, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Address'),
        ),
    ]
