# Generated by Django 2.2.12 on 2020-11-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_auto_20201114_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stghealthfacility',
            unique_together=set(),
        ),
    ]
