# Generated by Django 2.1.2 on 2020-07-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_auto_20200731_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stghealthfacility',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Health Facility', 'verbose_name_plural': '  Health Facilities'},
        ),
        migrations.AlterModelOptions(
            name='stghealthfacilitytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Health Facility Translation'},
        ),
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='infrastructure',
        ),
        migrations.AddField(
            model_name='stghealthfacility',
            name='infrastructure',
            field=models.ManyToManyField(blank=True, db_table='stg_infrastructure_lookup', to='facilities.StgFacilityInfrastructure', verbose_name='Health Infratructures'),
        ),
    ]
