# Generated by Django 2.2.12 on 2020-11-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_auto_20201114_1927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stghealthfacility',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='StgHealthFacilityTranslation',
        ),
    ]
