# Generated by Django 2.1.2 on 2020-08-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_auto_20200731_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgfacilityinfrastructure',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Infratsrucrure', 'verbose_name_plural': 'Health Infrastructures'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilityownership',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Facility Owner', 'verbose_name_plural': 'Facility Owners'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilityownershiptranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Facility Owner Translation'},
        ),
        migrations.AlterModelOptions(
            name='stghealthfacility',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Health Facility', 'verbose_name_plural': 'Health Facilities'},
        ),
        migrations.AlterModelOptions(
            name='stgservicedomain',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Service Domain', 'verbose_name_plural': 'Service Domains'},
        ),
        migrations.RemoveField(
            model_name='stgservicedomaintranslation',
            name='level',
        ),
        migrations.AddField(
            model_name='stgservicedomain',
            name='level',
            field=models.CharField(choices=[('Level 0', 'Level 0'), ('level 1', 'level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('Level 9', 'Level 9'), ('Level 10', 'Level 10')], default='Level 0', max_length=50, verbose_name='Domain Level'),
        ),
        migrations.AlterField(
            model_name='stgfacilityinfrastructure',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stgfacilityinfrastructure',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgfacilityinfrastructuretranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownership',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownership',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownership',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgfacilityownershiptranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stgfacilitytype',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgfacilitytypetranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityOwnership', verbose_name='Facility Owner'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='year_established',
            field=models.IntegerField(blank=True, default=2020, null=True, verbose_name='Year Established'),
        ),
        migrations.AlterField(
            model_name='stgservicedomain',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stgservicedomain',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgservicedomaintranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stgservicedomaintranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Domain Name'),
        ),
    ]
