# Generated by Django 2.2.12 on 2020-11-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_stghealthfacilitytranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StgHealthFacilityTranslation',
        ),
    ]
