# Generated by Django 2.1.2 on 2020-09-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_auto_20200810_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgfacilityinfrastructure',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Infratsrucrure', 'verbose_name_plural': 'Health Infrastructures'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilityownership',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Facility Owner', 'verbose_name_plural': 'Facility Owners'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilitytype',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Facility Type', 'verbose_name_plural': 'Facility Types'},
        ),
        migrations.AlterModelOptions(
            name='stghealthfacility',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Health Facility', 'verbose_name_plural': 'Health Facilities'},
        ),
        migrations.AlterModelOptions(
            name='stgservicedomain',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Service Domain', 'verbose_name_plural': 'Service Domains'},
        ),
    ]
