# Generated by Django 2.1.2 on 2020-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_auto_20200914_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgfacilityownership',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Facility Owner', 'verbose_name_plural': ' Facility Owners'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilitytype',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Facility Type', 'verbose_name_plural': '  Facility Types'},
        ),
        migrations.AlterModelOptions(
            name='stghealthfacility',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Health Facility', 'verbose_name_plural': '   Health Facilities'},
        ),
    ]
