# Generated by Django 2.1.2 on 2020-10-24 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_auto_20201002_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgfacilityinfrastructure',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Infrastructure', 'verbose_name_plural': 'Health Infrastructures'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilityinfrastructuretranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Infrastructure Translation'},
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone format: '+999999999' maximum 15.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
