# Generated by Django 2.1.2 on 2021-02-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_stghealthfacilitytranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgservicedomain',
            name='facilities',
        ),
    ]
