# Generated by Django 2.1.2 on 2021-02-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_facilityserviceavilability'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthfacility',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='facilities.FacilityServiceAvilability', verbose_name='Facility Services'),
            preserve_default=False,
        ),
    ]
