# Generated by Django 2.1.2 on 2021-02-12 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_stghealthfacility_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='availability',
        ),
        migrations.AddField(
            model_name='facilityserviceavilability',
            name='facility',
            field=models.ForeignKey(default=104215, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgHealthFacility', verbose_name='Facility Name'),
            preserve_default=False,
        ),
    ]
