# Generated by Django 2.1.2 on 2021-02-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_auto_20210212_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityserviceavailabilityproxy',
            options={'managed': False, 'verbose_name': 'Service Availability', 'verbose_name_plural': '  Services Availability Form'},
        ),
        migrations.AlterModelOptions(
            name='stgfacilityownership',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Facility Owner', 'verbose_name_plural': ' Facilities Ownerhip'},
        ),
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='facilityserviceavilability',
            name='domain',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgServiceDomain', verbose_name='Service Domain'),
        ),
    ]
