# Generated by Django 2.1.2 on 2021-02-14 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0020_auto_20210214_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='phone_code',
            field=models.CharField(choices=[('+242', '+242'), ('+244', '+244'), ('+254', '+254'), ('+256', '+256'), (' +263', ' +263')], default='+242', max_length=50, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='phone_part',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Format:'999999999' min 8, maximum 15.", regex='^[0-9]{8,15}$')], verbose_name='Phone Number'),
        ),
    ]
