# Generated by Django 2.1.2 on 2021-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0021_auto_20210214_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='phone_code',
            field=models.CharField(choices=[('+242', '+242'), ('+244', '+244'), ('+254', '+254'), ('+256', '+256'), (' +263', ' +263')], default='+242', max_length=5, verbose_name='Country Code'),
        ),
    ]
