# Generated by Django 2.1.2 on 2021-02-23 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0022_auto_20210214_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityserviceavailabilityproxy',
            options={'managed': False, 'verbose_name': 'Service Availability', 'verbose_name_plural': '  Services Availability'},
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityOwnership', verbose_name='Facility Ownership'),
        ),
    ]
