# Generated by Django 2.1.2 on 2021-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0024_facilityserviceprovision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityserviceprovision',
            name='functional',
            field=models.PositiveIntegerField(help_text='Functional units used in the last month', verbose_name='Number Functional'),
        ),
    ]
