# Generated by Django 2.1.2 on 2021-02-23 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0025_auto_20210223_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityServiceReadiness',
            fields=[
                ('readiness_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=45, unique=True)),
                ('units', models.CharField(choices=[('NCD HPR', 'NCD HPR'), ('CD health HPR', 'Child health HPR'), ('Child health HPR', 'Child health HPR'), ('Adolescent health HPR ', 'Adolescent health HPR'), ('Adult health HPR', 'Adult health HPR'), ('Elderly health HPR', 'Elderly health HPR')], default='NCD HPR', max_length=50, verbose_name='Units of Provision')),
                ('available', models.PositiveIntegerField(help_text='The input must be a zero or positive integer', verbose_name='Number available')),
                ('functional', models.PositiveIntegerField(help_text='Number of units needed for adequacy', verbose_name='Number needed')),
                ('start_period', models.DateField(auto_now_add=True, help_text='Start of reporting period', verbose_name='Start Date')),
                ('end_period', models.DateField(auto_now_add=True, help_text='End of reporting period', verbose_name='End Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('domain', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgServiceDomain', verbose_name='Provision Domain')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgHealthFacility', verbose_name='Facility Name')),
            ],
            options={
                'verbose_name': 'Service Readiness',
                'verbose_name_plural': 'Service Readiness',
                'db_table': 'stg_facility_services_readiness',
                'ordering': ('domain',),
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='facilityserviceprovision',
            name='units',
            field=models.CharField(choices=[('NCD HPR', 'NCD HPR'), ('CD health HPR', 'Child health HPR'), ('Child health HPR', 'Child health HPR'), ('Adolescent health HPR ', 'Adolescent health HPR'), ('Adult health HPR', 'Adult health HPR'), ('Elderly health HPR', 'Elderly health HPR')], default='NCD HPR', max_length=50, verbose_name='Units of Provision'),
        ),
    ]
