# Generated by Django 2.1.2 on 2021-02-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0026_auto_20210223_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgservicedomain',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Availability'), (2, 'Capacity'), (3, 'Readiness')], default=1, verbose_name='Service Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilityservicereadiness',
            name='domain',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgServiceDomain', verbose_name='Readiness Domain'),
        ),
    ]
