# Generated by Django 2.1.2 on 2021-02-28 10:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0027_auto_20210228_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgFacilityServiceIntervention',
            fields=[
                ('intervention_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Intervention Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Facility Servce Intervention',
                'verbose_name_plural': '  Service Interventions',
                'db_table': 'stg_facility_service_intervention',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgFacilityServiceInterventionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Intervention Name')),
                ('shortname', models.CharField(max_length=50, unique=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='facilities.StgFacilityServiceIntervention')),
            ],
            options={
                'verbose_name': 'Facility Servce Intervention Translation',
                'db_table': 'stg_facility_service_intervention_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='stgservicedomain',
            name='level',
            field=models.CharField(choices=[('Level 0', 'Level 0'), ('level 1', 'level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('Level 9', 'Level 9'), ('Level 10', 'Level 10')], default='Level 0', max_length=50, verbose_name='Category Level'),
        ),
        migrations.AlterField(
            model_name='stgservicedomaintranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='stgservicedomaintranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Service Name'),
        ),
        migrations.AlterUniqueTogether(
            name='stgfacilityserviceinterventiontranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
