# Generated by Django 2.1.2 on 2021-02-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0029_auto_20210228_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityServiceAvilability',
            new_name='FacilityServiceAvailability',
        ),
        migrations.AddField(
            model_name='stgfacilityserviceintervention',
            name='domain',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgServiceDomain', verbose_name='Service Domain'),
            preserve_default=False,
        ),
    ]
