# Generated by Django 2.1.2 on 2021-02-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0032_auto_20210228_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityserviceavailability',
            unique_together={('domain', 'facility', 'intervention', 'service', 'start_period', 'end_period')},
        ),
    ]
