# Generated by Django 2.1.2 on 2021-02-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0033_auto_20210228_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityServiceProvisionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Service Capacity',
                'verbose_name_plural': '  Service Capacity',
                'managed': False,
                'proxy': True,
            },
            bases=('facilities.stghealthfacility',),
        ),
        migrations.CreateModel(
            name='FacilityServiceReadinesProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Service Readiness',
                'verbose_name_plural': '  Service Readiness',
                'managed': False,
                'proxy': True,
            },
            bases=('facilities.stghealthfacility',),
        ),
        migrations.AlterModelOptions(
            name='facilityserviceavailabilityproxy',
            options={'managed': False, 'verbose_name': 'Service Availability', 'verbose_name_plural': '  Service Availability'},
        ),
        migrations.RenameField(
            model_name='facilityservicereadiness',
            old_name='functional',
            new_name='require',
        ),
    ]
