# Generated by Django 2.1.2 on 2021-02-28 17:21

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0034_auto_20210228_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgFacilityServiceMeasureUnits',
            fields=[
                ('infra_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Provision Unit',
                'verbose_name_plural': 'Provision Units',
                'db_table': 'stg_facility_service_units',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgFacilityServiceMeasureUnitsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Units of Provision')),
                ('shortname', models.CharField(max_length=50, unique=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='facilities.StgFacilityServiceMeasureUnits')),
            ],
            options={
                'verbose_name': 'Provision Unit Translation',
                'db_table': 'stg_facility_service_units_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='stgfacilityinfrastructuretranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stgfacilityinfrastructuretranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='stgservicedomain',
            name='level',
            field=models.CharField(choices=[('Level 0', 'Level 0'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], default='Level 0', max_length=50, verbose_name='Category Level'),
        ),
        migrations.DeleteModel(
            name='StgFacilityInfrastructure',
        ),
        migrations.DeleteModel(
            name='StgFacilityInfrastructureTranslation',
        ),
        migrations.AddField(
            model_name='stgfacilityservicemeasureunits',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgServiceDomain', verbose_name='Service Category'),
        ),
        migrations.AlterUniqueTogether(
            name='stgfacilityservicemeasureunitstranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
