# Generated by Django 2.1.2 on 2021-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0035_auto_20210228_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgfacilityservicemeasureunitstranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Units of Provision Name'),
        ),
        migrations.AlterField(
            model_name='stgfacilityservicemeasureunitstranslation',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Short Name'),
        ),
    ]
