# Generated by Django 2.1.2 on 2021-02-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0036_auto_20210228_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityserviceprovision',
            name='units',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityServiceMeasureUnits', verbose_name='Units of Provision'),
        ),
    ]
