# Generated by Django 2.1.2 on 2021-02-28 19:01

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0014_auto_20201024_0911'),
        ('facilities', '0038_auto_20210228_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgFacilityLocation',
            fields=[
                ('location', models.OneToOneField(help_text='You are not allowed to make changes to this Field because it             is related to countries already registed', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='regions.StgLocation', verbose_name='Country')),
                ('country_code', models.CharField(max_length=15, unique=True, verbose_name='ISO Alpha Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': '   Countries',
                'db_table': 'stg_facility_location',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
