# Generated by Django 2.1.2 on 2021-02-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0039_stgfacilitylocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgfacilitylocation',
            options={'managed': True, 'ordering': ('location',), 'verbose_name': 'Country', 'verbose_name_plural': '   Countries'},
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityLocation', verbose_name='Country'),
        ),
    ]
