# Generated by Django 2.1.2 on 2021-03-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0040_auto_20210228_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgfacilitylocation',
            options={'managed': True, 'ordering': ('location',), 'verbose_name': 'Country Code', 'verbose_name_plural': 'Facilities Country'},
        ),
    ]
