# Generated by Django 2.1.2 on 2021-03-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0041_auto_20210301_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='phone_code',
        ),
        migrations.AddField(
            model_name='stghealthfacility',
            name='country_code',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityLocation', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Country'),
        ),
    ]
