# Generated by Django 2.1.2 on 2021-03-01 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0042_auto_20210301_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='country_code',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityLocation', verbose_name='Country'),
        ),
    ]
