# Generated by Django 2.1.2 on 2021-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0046_auto_20210303_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityservicereadiness',
            name='end_period',
            field=models.IntegerField(default=2021, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='facilityservicereadiness',
            name='start_period',
            field=models.IntegerField(default=2021, help_text='This marks the start of reporting period', verbose_name='Starting period'),
        ),
    ]
