# Generated by Django 2.1.2 on 2021-03-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0047_auto_20210303_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stghealthfacility',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityLocation', verbose_name='Facility Country'),
        ),
    ]
