# Generated by Django 2.1.2 on 2021-03-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0048_auto_20210304_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthfacility',
            name='phone_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Code'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='location',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='facilities.StgFacilityLocation', verbose_name='Facility Country'),
        ),
    ]
