# Generated by Django 2.1.2 on 2021-03-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0049_auto_20210304_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgfacilitylocation',
            name='location',
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='location',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocationCodes', verbose_name='Facility Country'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='phone_code',
            field=models.CharField(blank=True, help_text='Specific country code for the phone number such as +242 is         automatically retrieved from database of AFRO member countries', max_length=5, verbose_name='Phone Code'),
        ),
        migrations.DeleteModel(
            name='StgFacilityLocation',
        ),
    ]
