# Generated by Django 2.1.2 on 2021-03-04 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0051_facilityserviceavailability_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityserviceprovision',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin User (Email)'),
        ),
        migrations.AddField(
            model_name='facilityservicereadiness',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin User (Email)'),
        ),
        migrations.AlterField(
            model_name='facilityserviceavailability',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin User (Email)'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin User (Email)'),
        ),
    ]
