# Generated by Django 2.1.2 on 2021-03-05 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0052_auto_20210304_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacility',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone format: '+999999999' maximum 15.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telephone'),
        ),
    ]
