# Generated by Django 2.1.2 on 2020-07-27 09:19

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20200727_1126'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aho_factsindicator_archive',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator')),
                ('value_received', models.DecimalField(decimal_places=10, max_digits=20, null=True, verbose_name='Value')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('start_period', models.IntegerField(default=2020, help_text='This Year marks the start of the reporting period.             NB: 1990 is the Lowest Limit!', verbose_name='Start Year')),
                ('end_period', models.IntegerField(default=2020, help_text='This Year marks the end of reporting.         The value must be current year or greater than the start year', verbose_name='Ending Year')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Approval Status')),
                ('string_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value [Remarks]')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'db_table': 'aho_factsindicator_archive',
                'ordering': ('indicator__name', 'location__name'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AhoDoamain_Lookup',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=500, verbose_name='Indicator Name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Indicator Code')),
                ('domain_name', models.CharField(blank=True, max_length=230, verbose_name='Domain Name  ')),
                ('domain_level', models.IntegerField(verbose_name='Domain Level')),
            ],
            options={
                'verbose_name': 'Domain Lookup',
                'verbose_name_plural': ' Domains Lookup',
                'db_table': 'aho_domain_lookup',
                'ordering': ('indicator_name',),
                'managed': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgAnalyticsNarrative',
            fields=[
                ('analyticstext_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Narrative Code')),
                ('narrative_text', models.TextField(verbose_name=' Narrative Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorDomain', verbose_name='Indicator Domain')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Theme Narrative',
                'verbose_name_plural': 'Thematic Narratives',
                'db_table': 'stg_analytics_narrative',
                'ordering': ('-narrative_type',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorNarrative',
            fields=[
                ('indicatornarrative_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Narrative Code')),
                ('narrative_text', models.TextField(verbose_name=' Narrative Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Indicator Narrative',
                'verbose_name_plural': 'Indicator Narratives',
                'db_table': 'stg_indicator_narrative',
                'ordering': ('-narrative_type',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgNarrative_Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Narrative Type')),
                ('shortname', models.CharField(max_length=120, null=True, unique=True, verbose_name='Short Name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Narrative Code')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Narrative Type',
                'verbose_name_plural': 'Narrative Types',
                'db_table': 'stg_narrative_type',
                'ordering': ('name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='narrative_type',
            field=models.ForeignKey(db_column='narrative_type_id', on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type'),
        ),
        migrations.AddField(
            model_name='stganalyticsnarrative',
            name='narrative_type',
            field=models.ForeignKey(db_column='narrative_type_id', on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type'),
        ),
    ]
