# Generated by Django 2.1.2 on 2020-07-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20200727_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahodoamain_lookup',
            options={'managed': False, 'ordering': ('indicator_name',), 'verbose_name': 'Lookup Theme', 'verbose_name_plural': ' Lookup Themes'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatordomain',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Indicator Theme', 'verbose_name_plural': ' Indicator Themes'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatordomaintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Indicator Theme Translation'},
        ),
        migrations.AlterField(
            model_name='stgindicatordomain',
            name='code',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stgindicatordomain',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorDomain', verbose_name='Main Theme'),
        ),
        migrations.AlterField(
            model_name='stgindicatordomaintranslation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Theme Name'),
        ),
    ]
