# Generated by Django 2.1.2 on 2020-07-27 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_stgindicatorreference_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='factdataindicator',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgindicator',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgindicatordomain',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
