# Generated by Django 2.1.2 on 2020-07-27 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20200727_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
