# Generated by Django 2.1.2 on 2020-07-27 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20200727_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='stganalyticsnarrative',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgindicatornarrative',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgnarrative_type',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
