# Generated by Django 2.1.2 on 2020-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20200727_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgindicatortranslation',
            name='gen_code',
        ),
        migrations.AddField(
            model_name='stgindicator',
            name='gen_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Geneva Code'),
        ),
    ]
