# Generated by Django 2.1.2 on 2020-07-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20200729_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgindicatorreference',
            options={'managed': True, 'verbose_name': 'Indicator Reference', 'verbose_name_plural': ' Indicator References'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatorreferencetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Indicator Reference Translation'},
        ),
    ]
