# Generated by Django 2.1.2 on 2020-07-31 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200731_1246'),
        ('indicators', '0010_auto_20200730_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='factdataindicator',
            name='measuremethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Type of Measure'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='value_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Data Value'),
        ),
    ]
