# Generated by Django 2.1.2 on 2020-07-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20200731_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factdataindicator',
            name='valuetype',
        ),
        migrations.RemoveField(
            model_name='stgindicator',
            name='measuremethod',
        ),
    ]
