# Generated by Django 2.1.2 on 2020-08-10 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20200810_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgindicatordomaintranslation',
            name='level',
        ),
        migrations.AddField(
            model_name='stgindicatordomain',
            name='level',
            field=models.CharField(choices=[('Level 0', 'Level 0'), ('level 1', 'level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('Level 9', 'Level 9'), ('Level 10', 'Level 10')], default='Level 0', max_length=50, verbose_name='Theme Level'),
        ),
        migrations.AlterField(
            model_name='stgindicatorreference',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
    ]
