# Generated by Django 2.1.2 on 2020-08-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_auto_20200810_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataindicator',
            options={'managed': True, 'ordering': ('location__name',), 'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')), 'verbose_name': 'Indicator Record', 'verbose_name_plural': 'Single-Record Form'},
        ),
        migrations.AlterField(
            model_name='stgindicatornarrative',
            name='narrative_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type'),
        ),
    ]
