# Generated by Django 2.1.2 on 2020-08-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_auto_20200810_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aho_factsindicator_archive',
            options={'managed': False, 'ordering': ('location__name',), 'verbose_name': 'Archive', 'verbose_name_plural': 'Indicators Archive'},
        ),
    ]
