# Generated by Django 2.1.2 on 2020-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0017_auto_20200810_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgindicatordomain',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6')], default=1, verbose_name='Theme Level'),
        ),
    ]
