# Generated by Django 2.1.2 on 2020-09-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_auto_20200828_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataindicator',
            options={'managed': True, 'ordering': ('location__name',), 'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')), 'verbose_name': 'Indicator Record', 'verbose_name_plural': 'Single-record Form'},
        ),
    ]
