# Generated by Django 2.1.2 on 2020-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_auto_20200914_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='string_value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='value_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Data Value'),
        ),
    ]
