# Generated by Django 2.1.2 on 2020-09-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_auto_20200914_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgindicator',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatordomain',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Indicator Theme', 'verbose_name_plural': 'Indicator Themes'},
        ),
        migrations.AlterModelOptions(
            name='stgindicatorreference',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Indicator Reference', 'verbose_name_plural': 'Indicator References'},
        ),
        migrations.AlterModelOptions(
            name='stgnarrative_type',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Narrative Type', 'verbose_name_plural': 'Narrative Types'},
        ),
    ]
