# Generated by Django 2.1.2 on 2020-09-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_auto_20200919_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aho_factsindicator_archive',
            options={'managed': False, 'ordering': ('indicator__name', 'location__name'), 'verbose_name': 'Indicator Archive', 'verbose_name_plural': 'Indicators Archive'},
        ),
        migrations.AlterModelOptions(
            name='factdataindicator',
            options={'managed': True, 'ordering': ('indicator__name', 'location__name'), 'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')), 'verbose_name': 'Indicator Data Record', 'verbose_name_plural': 'Single-record Form'},
        ),
    ]
