# Generated by Django 2.2.12 on 2021-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_auto_20201002_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='end_period',
            field=models.IntegerField(default=2021, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='start_period',
            field=models.IntegerField(default=2021, help_text='This marks the start of reporting period', verbose_name='Starting period'),
        ),
    ]
