# Generated by Django 2.1.2 on 2020-07-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0007_stgresourcetypetranslation_categorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTypeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Human Resource',
                'verbose_name_plural': ' Human Resource & Guides',
                'proxy': True,
                'indexes': [],
            },
            bases=('publications.stgresourcetype',),
        ),
    ]
