# Generated by Django 2.1.2 on 2020-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0002_auto_20200731_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthcadretranslation',
            name='academic',
            field=models.CharField(choices=[('degree', 'Degree'), ('diploma', 'Diploma'), ('masters', 'Masters'), ('phd', 'Doctorate'), ('certificate', 'Certificate'), ('basic', 'Basic Education')], default='degree', max_length=10, verbose_name='Qualification Level'),
        ),
    ]
