# Generated by Django 2.1.2 on 2020-07-31 12:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0003_auto_20200731_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgInstitutionProgrammes',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': ' Programme',
                'verbose_name_plural': 'Institution Programmes',
                'db_table': 'stg_institution_programme',
                'ordering': ('code',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgInstitutionProgrammesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Resource Type Name')),
                ('shortname', models.CharField(blank=True, max_length=230, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health_workforce.StgInstitutionProgrammes')),
            ],
            options={
                'verbose_name': ' Programme Translation',
                'db_table': 'stg_institution_programme_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='stghealthcadre',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Health Cadre', 'verbose_name_plural': ' Health Cadres'},
        ),
        migrations.AlterModelOptions(
            name='stghealthcadretranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Health Cadre Translation'},
        ),
        migrations.RemoveField(
            model_name='stgtraininginstitutiontranslation',
            name='programmes',
        ),
        migrations.AlterField(
            model_name='stghealthcadretranslation',
            name='academic',
            field=models.CharField(choices=[('degree', 'Degree'), ('diploma', 'Diploma'), ('masters', 'Masters'), ('phd', 'Doctorate'), ('certificate', 'Certificate'), ('basic', 'Basic Education')], default='degree', max_length=10, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='stghealthcadretranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Cadre Name'),
        ),
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='categoryoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Options'),
        ),
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Data Value'),
        ),
        migrations.AlterUniqueTogether(
            name='stginstitutionprogrammestranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
