# Generated by Django 2.1.2 on 2020-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0004_auto_20200731_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgtraininginstitution',
            name='programmes',
            field=models.ManyToManyField(blank=True, db_table='stg_institution_programs_lookup', to='health_workforce.StgInstitutionProgrammes', verbose_name='Training Programmes'),
        ),
    ]
