# Generated by Django 2.1.2 on 2020-07-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0005_stgtraininginstitution_programmes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stginstitutionprogrammes',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': ' Programme', 'verbose_name_plural': 'Training Programmes'},
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Address/Person'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teaching Language'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='posta',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Postal Address'),
        ),
    ]
