# Generated by Django 2.1.2 on 2020-07-31 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0006_auto_20200731_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthcadre',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='health_workforce.StgHealthCadre', verbose_name='Parent Location'),
        ),
    ]
