# Generated by Django 2.1.2 on 2020-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0010_auto_20200818_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgrecurringeventtranslation',
            name='name',
            field=models.CharField(default='International Year of the Nurse and the Midwife', max_length=230, verbose_name='Event Name'),
        ),
    ]
