# Generated by Django 2.1.2 on 2020-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0011_auto_20200818_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='cadre_id',
            field=models.ManyToManyField(blank=True, db_table='stg_recurring_event_lookup', to='health_workforce.StgHealthCadre', verbose_name='Target Focus'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='code',
            field=models.CharField(blank=True, max_length=45, unique=True, verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='media/images/events', verbose_name='Upload Picture/Banner(s)'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='external_url',
            field=models.CharField(blank=True, max_length=2083, null=True, verbose_name='Web Link (URL)'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='internal_url',
            field=models.FileField(blank=True, upload_to='media/files/events', verbose_name='Upload File/Video(s)'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='status',
            field=models.CharField(choices=[('active', 'Open'), ('inactive', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stgrecurringeventtranslation',
            name='name',
            field=models.CharField(default='International Year of the Nurse and the Midwife', max_length=230, verbose_name='Name of Event'),
        ),
    ]
