# Generated by Django 2.1.2 on 2020-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0013_auto_20200818_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgannouncementstranslation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
