# Generated by Django 2.1.2 on 2020-09-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0014_auto_20200818_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgannouncements',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='stghealthcadre',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Health Cadre', 'verbose_name_plural': 'Health Cadres'},
        ),
        migrations.AlterModelOptions(
            name='stginstitutionprogrammes',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Training Programme', 'verbose_name_plural': 'Training Programmes'},
        ),
        migrations.AlterModelOptions(
            name='stginstitutiontype',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Institution Type', 'verbose_name_plural': 'Institution Types'},
        ),
        migrations.AlterModelOptions(
            name='stgrecurringevent',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Recurring Event', 'verbose_name_plural': 'Recurring Events'},
        ),
        migrations.AlterModelOptions(
            name='stgtraininginstitution',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Institution', 'verbose_name_plural': 'Training Institutions'},
        ),
    ]
