# Generated by Django 2.1.2 on 2020-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0015_auto_20200914_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stghealthcadre',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Health Cadre', 'verbose_name_plural': '   Health Cadres'},
        ),
        migrations.AlterModelOptions(
            name='stghealthworkforcefacts',
            options={'managed': True, 'ordering': ('cadre_id',), 'verbose_name': 'Healthworkforce Data', 'verbose_name_plural': '    Healthworkforce Data'},
        ),
        migrations.AlterModelOptions(
            name='stginstitutionprogrammes',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Training Programme', 'verbose_name_plural': ' Training Programmes'},
        ),
        migrations.AlterModelOptions(
            name='stginstitutiontype',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Institution Type', 'verbose_name_plural': ' Institution Types'},
        ),
        migrations.AlterModelOptions(
            name='stgrecurringevent',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Nursing & Midwifery', 'verbose_name_plural': 'Nursing and Midwifery'},
        ),
        migrations.AlterModelOptions(
            name='stgrecurringeventtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Nursing & Midwifery Translation'},
        ),
        migrations.AlterModelOptions(
            name='stgtraininginstitution',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Institution', 'verbose_name_plural': '  Training Institutions'},
        ),
    ]
