# Generated by Django 2.2.12 on 2021-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0017_auto_20201024_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stghealthworkforcefacts',
            options={'managed': True, 'ordering': ('cadre_id',), 'verbose_name': 'Health Workforce', 'verbose_name_plural': '    Health Workforce'},
        ),
        migrations.AlterField(
            model_name='stgannouncements',
            name='end_year',
            field=models.IntegerField(default=2021, verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='stgannouncements',
            name='start_year',
            field=models.IntegerField(default=2021, verbose_name='Starting Period'),
        ),
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='end_year',
            field=models.IntegerField(default=2021, verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='start_year',
            field=models.IntegerField(default=2021, verbose_name='Starting Period'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='end_year',
            field=models.IntegerField(default=2021, verbose_name='Ending Period'),
        ),
        migrations.AlterField(
            model_name='stgrecurringevent',
            name='start_year',
            field=models.IntegerField(default=2021, verbose_name='Starting Period'),
        ),
    ]
