# Generated by Django 2.1.2 on 2020-08-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=45, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Other', 'Other')], default='Male', max_length=45, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='user name'),
        ),
    ]
