# Generated by Django 2.2.12 on 2020-11-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200810_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahodctuserlogs',
            options={'managed': False, 'ordering': ('username',), 'verbose_name': 'View Users Log', 'verbose_name_plural': ' View User Logs'},
        ),
        migrations.AlterModelOptions(
            name='customgroup',
            options={'managed': True, 'verbose_name': 'System Role', 'verbose_name_plural': ' System Roles'},
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group', verbose_name='System Role'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='roles_manager',
            field=models.CharField(default='Staff', max_length=70, verbose_name='Roles Manager'),
        ),
    ]
