# Generated by Django 2.1.2 on 2021-03-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201114_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Role Manager Location'),
        ),
    ]
