# Generated by Django 2.1.2 on 2020-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgmeasuremethod',
            options={'managed': True, 'verbose_name': 'Indicator Type', 'verbose_name_plural': 'Indicator Measure Types'},
        ),
        migrations.AlterModelOptions(
            name='stgmeasuremethodtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Indicator Type Translation'},
        ),
        migrations.AlterModelOptions(
            name='stgvaluedatatype',
            options={'managed': True, 'verbose_name': ' Data Value', 'verbose_name_plural': 'Data Value Types'},
        ),
        migrations.AlterModelOptions(
            name='stgvaluedatatypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': ' Data Value Translation'},
        ),
        migrations.RemoveField(
            model_name='stgvaluedatatypetranslation',
            name='code',
        ),
        migrations.AddField(
            model_name='stgvaluedatatype',
            name='code',
            field=models.CharField(default='VAL001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stgvaluedatatypetranslation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Value Name'),
        ),
    ]
