# Generated by Django 2.1.2 on 2020-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200723_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgcategoryoptiontranslation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stgcategoryparenttranslation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stgdatasourcetranslation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stgmeasuremethodtranslation',
            name='code',
        ),
        migrations.AddField(
            model_name='stgcategoryoption',
            name='code',
            field=models.CharField(blank=True, max_length=230, unique=True),
        ),
        migrations.AddField(
            model_name='stgcategoryparent',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stgdatasource',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
