# Generated by Django 2.1.2 on 2020-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200727_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgmeasuremethod',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
