# Generated by Django 2.1.2 on 2020-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_stgmeasuremethod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgmeasuremethodtranslation',
            name='measure_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='Numeric Value'),
        ),
    ]
