# Generated by Django 2.1.2 on 2020-07-27 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_stgcategoryparent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgcategoryoption',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgdatasource',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgmeasuremethod',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgvaluedatatype',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
