# Generated by Django 2.1.2 on 2020-07-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200727_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgdatasourcetranslation',
            name='level',
            field=models.CharField(blank=True, help_text='Level can be global, regional, national orsubnational', max_length=50, null=True, verbose_name='Source Level'),
        ),
    ]
