# Generated by Django 2.1.2 on 2020-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stgdatasourcetranslation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdatasourcetranslation',
            name='level',
            field=models.CharField(choices=[('1', 'Global'), ('2', 'Regional'), ('3', 'National'), ('4', 'Sub-national'), ('5', 'Independent')], default='1', help_text='Level can be global, regional, national, subnational', max_length=2, verbose_name='Source Level'),
            preserve_default=False,
        ),
    ]
