# Generated by Django 2.1.2 on 2020-07-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200731_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgmeasuremethod',
            options={'managed': True, 'verbose_name': ' Measure Type', 'verbose_name_plural': 'Measure Types'},
        ),
    ]
