# Generated by Django 2.1.2 on 2020-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200731_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdatasourcetranslation',
            name='level',
            field=models.CharField(choices=[('global', 'Global'), ('regional', 'Regional'), ('national', 'National'), ('sub-national', 'Sub-national'), ('unspecified', 'Non-specific')], default='national', help_text='Level can be global, regional, national, subnational', max_length=20, verbose_name='Source Level'),
        ),
    ]
