# Generated by Django 2.1.2 on 2020-08-10 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200810_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgmeasuremethod',
            options={'managed': True, 'verbose_name': 'Measure Type', 'verbose_name_plural': 'Measure Types'},
        ),
        migrations.AlterModelOptions(
            name='stgmeasuremethodtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Measure Type Translation'},
        ),
        migrations.AlterField(
            model_name='stgcategoryoptiontranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Disaggregation Option'),
        ),
        migrations.AlterField(
            model_name='stgcategoryparenttranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='stgmeasuremethod',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgmeasuremethodtranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Measure Name'),
        ),
    ]
