# Generated by Django 2.1.2 on 2020-09-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200828_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgcategoryoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryParent', verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='stgcategoryoptiontranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Modality Name'),
        ),
    ]
