# Generated by Django 2.1.2 on 2020-09-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200906_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgcategoryoption',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Disaggregation Option', 'verbose_name_plural': 'Disaggregation Options'},
        ),
        migrations.AlterModelOptions(
            name='stgcategoryparent',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Disaggregation Category', 'verbose_name_plural': 'Disaggregation Categories'},
        ),
        migrations.AlterModelOptions(
            name='stgdatasource',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Data Source', 'verbose_name_plural': 'Data Sources'},
        ),
        migrations.AlterModelOptions(
            name='stgmeasuremethod',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Measure Type', 'verbose_name_plural': 'Measure Types'},
        ),
        migrations.AlterModelOptions(
            name='stgvaluedatatype',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': ' Data Value', 'verbose_name_plural': 'Data Value Types'},
        ),
    ]
