# Generated by Django 2.1.2 on 2020-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200914_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgcategoryoption',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Disaggregation Option', 'verbose_name_plural': '   Disaggregation Options'},
        ),
        migrations.AlterModelOptions(
            name='stgcategoryparent',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Disaggregation Category', 'verbose_name_plural': '  Disaggregation Categories'},
        ),
        migrations.AlterModelOptions(
            name='stgdatasource',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Data Source', 'verbose_name_plural': '    Data Sources'},
        ),
        migrations.AlterModelOptions(
            name='stgmeasuremethod',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Measure Type', 'verbose_name_plural': ' Measure Types'},
        ),
    ]
