# Generated by Django 2.1.2 on 2020-07-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20200723_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgspecialcategorization',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Special Categorization', 'verbose_name_plural': 'Special Categorizations'},
        ),
        migrations.AlterModelOptions(
            name='stgspecialcategorizationtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Special Categorization Translation'},
        ),
    ]
