# Generated by Django 2.1.2 on 2020-07-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200723_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stglocationtranslation',
            name='iso_alpha',
        ),
        migrations.RemoveField(
            model_name='stglocationtranslation',
            name='iso_number',
        ),
    ]
