# Generated by Django 2.1.2 on 2020-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20200727_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='stglocation',
            name='iso_alpha',
            field=models.CharField(default='AFR', max_length=15, unique=True, verbose_name='Alpha Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stglocation',
            name='iso_number',
            field=models.CharField(default='0001', max_length=15, unique=True, verbose_name='Numeric Code'),
            preserve_default=False,
        ),
    ]
