# Generated by Django 2.1.2 on 2020-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20200727_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgspecialcategorization',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'State Category', 'verbose_name_plural': 'State Categories'},
        ),
        migrations.AlterModelOptions(
            name='stgspecialcategorizationtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'State Category Translation'},
        ),
        migrations.AlterField(
            model_name='stgspecialcategorizationtranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='State Category'),
        ),
    ]
