# Generated by Django 2.1.2 on 2020-07-27 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_stglocationlevel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgworldbankincomegroups',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
