# Generated by Django 2.1.2 on 2020-09-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0011_auto_20200828_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgeconomiczones',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Economic Block', 'verbose_name_plural': 'Economic Blocks'},
        ),
        migrations.AlterModelOptions(
            name='stglocation',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='stglocationlevel',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Location Level', 'verbose_name_plural': 'Location Levels'},
        ),
        migrations.AlterModelOptions(
            name='stgspecialcategorization',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Categorization', 'verbose_name_plural': 'Special Categorizations'},
        ),
        migrations.AlterModelOptions(
            name='stgworldbankincomegroups',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Income Group', 'verbose_name_plural': 'Income Groups'},
        ),
    ]
