# Generated by Django 2.1.2 on 2020-10-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0013_auto_20201002_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stglocation',
            name='iso_alpha',
            field=models.CharField(max_length=15, unique=True, verbose_name='ISO Alpha Code'),
        ),
        migrations.AlterField(
            model_name='stglocation',
            name='iso_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='ISO Numeric Code'),
        ),
        migrations.AlterField(
            model_name='stglocation',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, help_text='You are not allowed to edit this field because it is        related to other records', null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Parent Location'),
        ),
        migrations.AlterField(
            model_name='stglocationleveltranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stglocationtranslation',
            name='cordinate',
            field=models.TextField(blank=True, null=True, verbose_name='Cordinates'),
        ),
        migrations.AlterField(
            model_name='stglocationtranslation',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='stglocationtranslation',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
