# Generated by Django 2.1.2 on 2020-07-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20200723_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgproductdomain',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Resource Theme', 'verbose_name_plural': ' Resource Themes'},
        ),
        migrations.AlterModelOptions(
            name='stgproductdomaintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Resource Theme Translation'},
        ),
        migrations.AlterField(
            model_name='stgproductdomain',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Theme Code'),
        ),
        migrations.AlterField(
            model_name='stgproductdomain',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.StgProductDomain', verbose_name='Main Theme'),
        ),
        migrations.AlterField(
            model_name='stgproductdomain',
            name='publications',
            field=models.ManyToManyField(blank=True, db_table='stg_product_domain_members', to='publications.StgKnowledgeProduct', verbose_name='Resources'),
        ),
        migrations.AlterField(
            model_name='stgproductdomaintranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Theme Name'),
        ),
    ]
