# Generated by Django 2.1.2 on 2020-07-27 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_stgresourcetype_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgknowledgeproduct',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgproductdomain',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
