# Generated by Django 2.1.2 on 2020-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20200728_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgresourcetypetranslation',
            name='categorization',
            field=models.CharField(choices=[('publications', 'publications'), ('health_workforce', 'health_workforce'), ('general', 'general')], default='publications', max_length=50, verbose_name='Category'),
        ),
    ]
