# Generated by Django 2.1.2 on 2020-08-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_stgresourcetypetranslation_categorization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgknowledgeproduct',
            options={'managed': True, 'ordering': ('code',), 'permissions': (('approve_stgknowledgeproduct', 'Can approve stgknowledgeproduct'), ('reject_stgknowledgeproduct', 'Can reject stgknowledgeproduct'), ('pend_stgknowledgeproduct', 'Can pend stgknowledgeproduct')), 'verbose_name': 'Knowledge Resource', 'verbose_name_plural': 'Knowledge Resources'},
        ),
        migrations.AlterModelOptions(
            name='stgproductdomain',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Resource Theme', 'verbose_name_plural': 'Resource Themes'},
        ),
        migrations.AlterField(
            model_name='stgknowledgeproduct',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='media/images', verbose_name='Cover Picture'),
        ),
        migrations.AlterField(
            model_name='stgknowledgeproduct',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='stgknowledgeproduct',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgknowledgeproducttranslation',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract/Summary'),
        ),
        migrations.AlterField(
            model_name='stgknowledgeproducttranslation',
            name='categorization',
            field=models.CharField(choices=[('toolkit', 'Toolkit'), ('publication', 'Publication')], default='toolkit', help_text='You must specify the published resource as a scienctific             publication or a toolkit.Toolkit are resources like  M&E Guides ', max_length=15, verbose_name='Resource Category'),
        ),
        migrations.AlterField(
            model_name='stgknowledgeproducttranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stgproductdomain',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.StgProductDomain', verbose_name='Parent Theme'),
        ),
        migrations.AlterField(
            model_name='stgproductdomain',
            name='publications',
            field=models.ManyToManyField(blank=True, db_table='stg_product_domain_members', to='publications.StgKnowledgeProduct', verbose_name='Knowledge Resources'),
        ),
        migrations.AlterField(
            model_name='stgproductdomain',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgproductdomaintranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stgproductdomaintranslation',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Theme level'),
        ),
        migrations.AlterField(
            model_name='stgproductdomaintranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Resource Theme'),
        ),
        migrations.AlterField(
            model_name='stgresourcetype',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgresourcetypetranslation',
            name='categorization',
            field=models.CharField(choices=[('publications', 'publications'), ('health_workforce', 'health_workforce'), ('general', 'general')], default='publications', max_length=50, verbose_name='Resource Category'),
        ),
        migrations.AlterField(
            model_name='stgresourcetypetranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='stgresourcetypetranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Type Name'),
        ),
    ]
