# Generated by Django 2.1.2 on 2020-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20200914_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgknowledgeproduct',
            options={'managed': True, 'ordering': ('translations__title',), 'permissions': (('approve_stgknowledgeproduct', 'Can approve stgknowledgeproduct'), ('reject_stgknowledgeproduct', 'Can reject stgknowledgeproduct'), ('pend_stgknowledgeproduct', 'Can pend stgknowledgeproduct')), 'verbose_name': 'Knowledge Resource', 'verbose_name_plural': '   Knowledge Resources'},
        ),
        migrations.AlterModelOptions(
            name='stgproductdomain',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Resource Theme', 'verbose_name_plural': '  Resource Themes'},
        ),
        migrations.AlterModelOptions(
            name='stgresourcecategory',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Resource Category', 'verbose_name_plural': ' Resource Categories'},
        ),
    ]
