# Generated by Django 2.1.2 on 2020-10-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20201002_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgknowledgeproducttranslation',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
