# Generated by Django 2.2.12 on 2021-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20201024_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgknowledgeproducttranslation',
            name='year_published',
            field=models.IntegerField(default=2021, verbose_name='Year Published'),
        ),
    ]
