# Generated by Django 2.1.2 on 2020-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdataelementgroup',
            name='dataelement',
            field=models.ManyToManyField(blank=True, db_table='stg_data_element_membership', to='elements.StgDataElement', verbose_name='Data Elements'),
        ),
    ]
