# Generated by Django 2.1.2 on 2020-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20200723_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stgdataelement',
            name='measuremethod',
        ),
        migrations.RemoveField(
            model_name='stgdataelementtranslation',
            name='aggregation_type',
        ),
        migrations.AddField(
            model_name='stgdataelement',
            name='aggregation_type',
            field=models.CharField(choices=[('Sum', 'Sum'), ('Average', 'Average'), ('Count', 'Count'), ('Standard Deviation', 'Standard Deviation'), ('Variance', 'Variance'), ('Min', 'Min'), ('max', 'max'), ('None', 'None')], default='Sum', max_length=45, verbose_name='Data Aggregation'),
        ),
    ]
