# Generated by Django 2.1.2 on 2020-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20200727_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgdataelement',
            options={'managed': True, 'ordering': ('code',), 'verbose_name': 'Element', 'verbose_name_plural': 'Data Elements'},
        ),
        migrations.AlterField(
            model_name='stgdataelement',
            name='aggregation_type',
            field=models.CharField(choices=[('Count', 'Count'), ('Sum', 'Sum'), ('Average', 'Average'), ('Standard Deviation', 'Standard Deviation'), ('Variance', 'Variance'), ('Min', 'Min'), ('max', 'max'), ('None', 'None')], default='Count', max_length=45, verbose_name='Data Aggregation'),
        ),
        migrations.AlterModelTable(
            name='stgdataelement',
            table='stg_data_element',
        ),
        migrations.AlterModelTable(
            name='stgdataelementtranslation',
            table='stg_data_element_translation',
        ),
    ]
