# Generated by Django 2.1.2 on 2020-07-27 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_auto_20200727_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataelementproxy',
            options={'verbose_name': 'Multi_Records Form', 'verbose_name_plural': ' Multi_Records Form'},
        ),
        migrations.AddField(
            model_name='factdataelement',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgdataelement',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Unique Universal ID'),
        ),
        migrations.AddField(
            model_name='stgdataelementgroup',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='Unique Universal ID'),
        ),
    ]
