# Generated by Django 2.1.2 on 2020-07-27 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_auto_20200727_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataelement',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
        migrations.AlterField(
            model_name='stgdataelementgroup',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID'),
        ),
    ]
