# Generated by Django 2.1.2 on 2020-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_auto_20200727_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdataelement',
            name='aggregation_type',
            field=models.CharField(choices=[('Count', 'Count'), ('Sum', 'Sum'), ('Average', 'Average'), ('Standard Deviation', 'Standard Deviation'), ('Variance', 'Variance'), ('Min', 'Min'), ('max', 'max'), ('None', 'None')], default='Count', max_length=45, verbose_name='Aggregate Type'),
        ),
    ]
