# Generated by Django 2.1.2 on 2020-08-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_auto_20200729_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataelement',
            options={'managed': True, 'ordering': ('location',), 'permissions': (('approve_factdataelement', 'Can approve Data Element'), ('reject_factdataelement', 'Can reject Data Element'), ('pend_factdataelement', 'Can pend Data Element')), 'verbose_name': 'Data Element', 'verbose_name_plural': 'Single-Record Form'},
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='comment',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='dataelement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elements.StgDataElement', verbose_name='Data Element'),
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Data Value'),
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='valuetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.StgValueDatatype', verbose_name='Value Type'),
        ),
        migrations.AlterField(
            model_name='stgdataelement',
            name='aggregation_type',
            field=models.CharField(choices=[('Count', 'Count'), ('Sum', 'Sum'), ('Average', 'Average'), ('Standard Deviation', 'Standard Deviation'), ('Variance', 'Variance'), ('Min', 'Min'), ('max', 'max'), ('None', 'None')], default='Count', max_length=45, verbose_name='aggregate Type'),
        ),
        migrations.AlterField(
            model_name='stgdataelementgroup',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='stgdataelementtranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stgdataelementtranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='stgdataelementtranslation',
            name='shortname',
            field=models.CharField(max_length=50, verbose_name='short name'),
        ),
    ]
