# Generated by Django 2.1.2 on 2020-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_auto_20200810_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgdataelementtranslation',
            name='name',
            field=models.CharField(max_length=230, verbose_name='Data Element Name'),
        ),
    ]
