# Generated by Django 2.1.2 on 2020-09-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_auto_20200828_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataelement',
            options={'managed': True, 'ordering': ('location',), 'permissions': (('approve_factdataelement', 'Can approve Data Element'), ('reject_factdataelement', 'Can reject Data Element'), ('pend_factdataelement', 'Can pend Data Element')), 'verbose_name': 'Raw Data Element', 'verbose_name_plural': 'Single-Record Form'},
        ),
    ]
