# Generated by Django 2.1.2 on 2020-10-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0012_auto_20200914_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataelementproxy',
            options={'verbose_name': 'Multi_Records Form', 'verbose_name_plural': '  Multi_Records Form'},
        ),
        migrations.AlterModelOptions(
            name='factdataelement',
            options={'managed': True, 'ordering': ('location',), 'permissions': (('approve_factdataelement', 'Can approve Data Element'), ('reject_factdataelement', 'Can reject Data Element'), ('pend_factdataelement', 'Can pend Data Element')), 'verbose_name': 'Data Element', 'verbose_name_plural': '   Single-Record Form'},
        ),
        migrations.AlterModelOptions(
            name='stgdataelementgroup',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'Element Group', 'verbose_name_plural': 'Element Groups'},
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='categoryoption',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Option'),
        ),
        migrations.AlterField(
            model_name='factdataelement',
            name='valuetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.StgValueDatatype', verbose_name='Data Type'),
        ),
    ]
