# Generated by Django 2.1.2 on 2021-03-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0015_auto_20210202_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='factdataelement',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name/Email'),
        ),
        migrations.AddField(
            model_name='stgdataelement',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name/Email'),
        ),
    ]
